name: conavigator
description: Conavigator client

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  copy_with_extension: ^2.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  latlong2: ^0.8.0
  flutter_map: ^0.13.1
  flutter_redux: ^0.8.2
  redux_saga: ^3.0.5
  geolocator: ^7.6.2
  logger: ^1.1.0
  http: ^0.13.3
  xml: ^5.3.0

dev_dependencies:
  copy_with_extension_gen: ^2.0.2
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
